"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.2.11.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIRS = os.path.join(BASE_DIR, 'templates')

# Chargement des variables d'environnement (.env)
load_dotenv()

# SÉCURITÉ : Récupère la clé de Render en production, utilise une clé de secours en local
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure--thh=0+@)9ohtmks_$naxakj!!z#ql9^%l840rq0*6am4u6al-')

# SÉCURITÉ : DEBUG passe automatiquement à False en production si la variable d'environnement DEBUG=False est sur Render
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# Configuration des hôtes autorisés
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost,.onrender.com').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop', # Votre application e-commerce
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise doit être placé ici obligatoirement
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIRS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database Configuration (Neon en Production / SQLite en Local)
# https://djangoproject.com

DATABASES = {
    'default': dj_database_url.config(
        # Si DATABASE_URL est présent (Render), dj-database-url configure PostgreSQL pour Neon.
        # Sinon (votre machine), Django crée et utilise la base db.sqlite3 locale.
        default=os.environ.get('DATABASE_URL', f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        ssl_require=True
    )
}


# Password validation
# https://djangoproject.com

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://djangoproject.com

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://djangoproject.com

STATIC_URL = '/static/'

# Dossier où collectstatic va rassembler tous les fichiers statiques pour la production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Dossiers où Django va chercher les fichiers statiques pendant le développement
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Optimisation du stockage WhiteNoise pour compresser les fichiers statiques en production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://djangoproject.com

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
