# Generated by Django 3.2.7 on 2026-09-25 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(max_length=250, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoye', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('lu', models.BooleanField(default=False, verbose_name='Message lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoye'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_abonne', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-date_abonne'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-tag', help_text='Classe FontAwesome (ex: fa-laptop, fa-tshirt, fa-mobile-alt)', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de commande'),
        ),
        migrations.AddField(
            model_name='commande',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Paiement à la livraison (Cash on Delivery)'), ('MOBILE_MONEY', 'Orange Money / MTN Mobile Money'), ('CARD', 'Carte Bancaire (Visa / Mastercard)'), ('PAYPAL', 'PayPal')], default='COD', max_length=50, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('PROCESSING', 'En cours de préparation'), ('SHIPPED', 'En cours de livraison'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=30, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancien prix / Promo ($)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name="Mettre en avant sur la page d'accueil"),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=4.5, verbose_name='Note moyenne (sur 5)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=25, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de commande'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.TextField(verbose_name='Détails du panier (JSON)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='pays',
            field=models.CharField(max_length=300, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.CharField(max_length=200, verbose_name='Total payé'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(max_length=200, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='zipcode',
            field=models.CharField(max_length=300, verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=5000, verbose_name="URL de l'image principale"),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Prix actuel ($)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du produit'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Nom de l'auteur")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.IntegerField(choices=[(1, '1 étoiles'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=5, verbose_name='Note')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Avis produit',
                'verbose_name_plural': 'Avis produits',
                'ordering': ['-date_added'],
            },
        ),
    ]
